# fly.toml app configuration file generated for translantic-fragrant-shadow-830 on 2024-03-28T14:21:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'translantic-fragrant-shadow-830'
primary_region = 'mad'
console_command = '/rails/bin/rails console'

[build]

[processes]
  app = './bin/rails server'
  sidekiq = 'bundle exec sidekiq'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/translantic/public'
  url_prefix = '/'
