# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: translantics_development

test:
  <<: *default
  database: translantics_test

production:
  <<: *default
  database: translantics_production
  username: translantics
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>

staging:
  <<: *default
  database: translantics_staging
  username: translantics
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
